### ISSUE TITLE
Improve Keyboard Navigation

### ISSUE THREAD

**Issue by rendeer-pl** [rendeer-pl/VideoTrimmer#8]
The UI of Video Trimmer is suited for mouse navigation. However, small tweaks could be implemented to ensure that it is properly responding to most basic keyboard events:
* pressing **Tab** to navigate between fields,
* pressing **Enter** while focusing on input fields to confirm change,
* while focused on the player itself or on the timeline:
    * pressing **Space** to pause/unpause the video,
    * pressing **I** and **[** to try to set the starting timecode,
    * pressing **O** and **]** to try to set the ending timecode,
    * using **Left** and **Right** arrows to move between frames of the video.

**Comment by mmmmmmmmmmmmtaco** [comment]
hi how do i help

**Comment by rendeer-pl** [comment]
Hi, thanks for your interest in improving Video Trimmer!
To start, please take a look at this excellent guide on becoming an Open Source contributor, especially the section about submitting a contribution: https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution

In this particular issue, it would be great if you reviewed the Tab behavior of the app ([this tutorial might be helpful](https://wpf-tutorial.com/control-concepts/tab-order/)) and added necessary key binding for other events listed in the description of this issue ([this page from the .net documentation might be useful](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-detect-when-the-enter-key-pressed?view=netframeworkdesktop-4.8)).

Thanks!

**Comment by upizs** [comment]
@mmmmmmmmmmmmtaco Hi,
have you started on this issue already?
